// @generated automatically by Diesel CLI.

diesel::table! {
    /// Representation of the `project_default_tags` table.
    ///
    /// (Automatically generated by Diesel.)
    project_default_tags (project_id, tag_id) {
        /// The `project_id` column of the `project_default_tags` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        project_id -> Integer,
        /// The `tag_id` column of the `project_default_tags` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        tag_id -> Integer,
    }
}

diesel::table! {
    /// Representation of the `projects` table.
    ///
    /// (Automatically generated by Diesel.)
    projects (id) {
        /// The `id` column of the `projects` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Integer,
        /// The `name` column of the `projects` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Text,
        /// The `description` column of the `projects` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        description -> Nullable<Text>,
    }
}

diesel::table! {
    /// Representation of the `sessions` table.
    ///
    /// (Automatically generated by Diesel.)
    sessions (id) {
        /// The `id` column of the `sessions` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Integer,
        /// The `task_id` column of the `sessions` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        task_id -> Integer,
        /// The `start_at` column of the `sessions` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        start_at -> Timestamp,
        /// The `updated_at` column of the `sessions` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamp,
        /// The `end_at` column of the `sessions` table.
        ///
        /// Its SQL type is `Nullable<Timestamp>`.
        ///
        /// (Automatically generated by Diesel.)
        end_at -> Nullable<Timestamp>,
        /// The `pomodoro_state` column of the `sessions` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        pomodoro_state -> Text,
        /// The `paused` column of the `sessions` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        paused -> Bool,
    }
}

diesel::table! {
    /// Representation of the `tags` table.
    ///
    /// (Automatically generated by Diesel.)
    tags (id) {
        /// The `id` column of the `tags` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Integer,
        /// The `name` column of the `tags` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Text,
        /// The `description` column of the `tags` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        description -> Nullable<Text>,
    }
}

diesel::table! {
    /// Representation of the `task_tags` table.
    ///
    /// (Automatically generated by Diesel.)
    task_tags (task_id, tag_id) {
        /// The `task_id` column of the `task_tags` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        task_id -> Integer,
        /// The `tag_id` column of the `task_tags` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        tag_id -> Integer,
    }
}

diesel::table! {
    /// Representation of the `tasks` table.
    ///
    /// (Automatically generated by Diesel.)
    tasks (id) {
        /// The `id` column of the `tasks` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Integer,
        /// The `name` column of the `tasks` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Text,
        /// The `description` column of the `tasks` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        description -> Nullable<Text>,
        /// The `deadline` column of the `tasks` table.
        ///
        /// Its SQL type is `Nullable<Timestamp>`.
        ///
        /// (Automatically generated by Diesel.)
        deadline -> Nullable<Timestamp>,
        /// The `parent_id` column of the `tasks` table.
        ///
        /// Its SQL type is `Nullable<Integer>`.
        ///
        /// (Automatically generated by Diesel.)
        parent_id -> Nullable<Integer>,
        /// The `project_id` column of the `tasks` table.
        ///
        /// Its SQL type is `Nullable<Integer>`.
        ///
        /// (Automatically generated by Diesel.)
        project_id -> Nullable<Integer>,
    }
}

diesel::joinable!(project_default_tags -> projects (project_id));
diesel::joinable!(project_default_tags -> tags (tag_id));
diesel::joinable!(sessions -> tasks (task_id));
diesel::joinable!(task_tags -> tags (tag_id));
diesel::joinable!(task_tags -> tasks (task_id));
diesel::joinable!(tasks -> projects (project_id));

diesel::allow_tables_to_appear_in_same_query!(
    project_default_tags,
    projects,
    sessions,
    tags,
    task_tags,
    tasks,
);
