---
config:
  class:
    hideEmptyMembersBox: true
---
classDiagram
    direction TD

    class AppError {
        +Cli(CliArgumentError)
        +ConfigError(String)
        +Ui(UiError)
        +InvalidState(String)
    }

    class CliArgumentError {
        +EmptyArgument
        +ParseError(String)
    }

    class ConfigError {
        +Io(io::Error)
        +Serialization(serde_yml::Error)
    }

    class UiError {
        +TuiError(TuiError)
    }

    class TuiError {
        +Io(io::Error)
        +InitializeError(String)
    }

    class PomodoroError {
        +Running
        +NotRunning
        +UnexpectedState(String)
    }

    class SoundError {
        +DeviceSinkError(DeviceSinkError)
        +ConfigError(String)
        +Decode(DecoderError)
    }

    class RepoError {
        +Connection(String)
    }

    AppError ..> CliArgumentError
    AppError ..> ConfigError
    AppError ..> UiError
    AppError ..> InvalidState

    UiError ..> TuiError

    TuiError ..> Io

    PomodoroError ..> UnexpectedState

    SoundError ..> DeviceSinkError
    SoundError ..> Decode

    RepoError ..> Connection
