---
config:
  class:
    hideEmptyMembersBox: true
---
classDiagram
    direction TD

    class Error {
        +Cli(CliArgumentError)
        +Config(ConfigError)
        +Ui(UiError)
    }

    class CliArgumentError {
        +EmptyArgument
        +ParseError(String)
    }

    class ConfigError {
        +Io(io::Error)
        +Serialization(serde_yml::Error)
    }

    class UiError {
        +Tui(TuiError)
        +App(AppError)
        +Build(AppBuildError)
    }

    class TuiError {
        +Io(io::Error)
    }

    class PomodoroError {
        +Running
        +NotRunning
        +UnexpectedState(String)
    }

    class AppError {
        +Pomodoro(PomodoroError)
    }

    class AppBuildError {
        +MissingConfig
        +MissingPomodoro
        +MissingHomeView
        +MissingTimerView
        +MissingSettingsView
    }

    Error ..> CliArgumentError
    Error ..> ConfigError
    Error ..> UiError

    UiError ..> TuiError
    UiError ..> AppError
    UiError ..> AppBuildError

    TuiError ..> AppError

    AppError ..> PomodoroError
